<a href="https://colab.research.google.com/github/adasrinivas1229/REINFORCEMENT_LEARNING/blob/master/cartpole1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import gym
import numpy as np
env = gym.make("MountainCar-v0")
env.reset()
print(env.observation_space.high)
print(env.observation_space.low)
print(env.action_space.n)
DISCRETE_OS_SIZE = [20]*len(env.observation_space.high)
discrete_os_win_size = (env.observation_space.high-env.observation_space.low) / DISCRETE_OS_SIZE
print(discrete_os_win_size)
q_table = np.random.uniform(low=-2, high=0, size=(DISCRETE_OS_SIZE + [env.action_space.n]))
print(q_table.shape)
print(q_table)
"""
done = False
while not done:
    action = 2
    new_state,reward,done,_ = env.step(action)
    print(reward,new_state)
    env.render()
env.close()  """
    
               


[0.6  0.07]
[-1.2  -0.07]
3
[0.09  0.007]
(20, 20, 3)
[[[-1.86478122 -1.47571875 -0.74918571]
  [-1.6653483  -0.57547076 -0.92709453]
  [-1.58016245 -1.07973261 -0.76524527]
  ...
  [-1.06775085 -1.39343492 -0.4384131 ]
  [-0.80157717 -0.46412409 -1.14480151]
  [-0.9976718  -1.37061762 -0.10417631]]

 [[-0.54217388 -0.27725948 -1.92344961]
  [-0.84436727 -0.37735031 -0.49709955]
  [-0.22385302 -1.29519211 -1.20052036]
  ...
  [-0.68385722 -0.92055033 -0.20809669]
  [-1.84067137 -0.24501965 -0.31009557]
  [-1.16001732 -1.20714381 -0.33280795]]

 [[-0.75088531 -0.21230791 -0.02315727]
  [-0.09770432 -0.05291339 -0.24656358]
  [-1.10913336 -0.45273691 -1.92123286]
  ...
  [-0.29412535 -1.28458431 -1.96538913]
  [-1.33253329 -1.73109942 -0.6651667 ]
  [-1.3130184  -0.89003088 -0.87604731]]

 ...

 [[-0.32691783 -0.62048915 -0.34621328]
  [-1.62156255 -1.1929879  -1.89579659]
  [-1.86280027 -1.1636446  -0.68876345]
  ...
  [-0.49724041 -1.26451715 -1.54037102]
  [-0.94271392 -1.47002012 -1.

'\ndone = False\nwhile not done:\n    action = 2\n    new_state,reward,done,_ = env.step(action)\n    print(reward,new_state)\n    env.render()\nenv.close()  '